environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: i686-pc-windows-gnu

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;
  - rustc -Vv
  - cargo -V

build_script:
  - cargo build

test_script:
  - cargo test

